In [17]:
import matplotlib.pyplot as plt  #画图用
import numpy as np
import matplotlib
import xlrd 
cnc=np.empty([6,8],dtype=int) 
# %cnc: 
# % 第一行：cnc位置常量
# % 第二行：cnc工作变量，空闲为0，忙碌为1
# % 第三行：cnc工作时间，为常量560
# % 第四行：cnc上下料时间
# % 第五行：cnc预计完成时间
# % 第六行：cnc加工物料数
file1="./cnc数据.xls"
data = xlrd.open_workbook(file1) 
sheet = data.sheet_by_index(0)  #sheet为第一个
# for col in range(sheet.ncols):   
#     print(sheet.cell_value(0,col)) 
for row in range(sheet.nrows):
    for col in range(sheet.ncols):
        cnc[row,col]=sheet.cell_value(row,col)
cnc[5,:]=-1
print(cnc)


[[  1   2   3   4   5   6   7   8]
 [  0   0   0   0   0   0   0   0]
 [560 560 560 560 560 560 560 560]
 [ 28  31  28  31  28  31  28  31]
 [  0   0   0   0   0   0   0   0]
 [ -1  -1  -1  -1  -1  -1  -1  -1]]
