In [1]:
import numpy as np 
from scipy.optimize import linprog

a=np.array([-3100,-3100,-3100,-3800,-3800,-3800,-3500,-3500,-3500,-2850,-2850,-2850,0])
b=np.array([[1,1,1,0,0,0,0,0,0,0,0,0,0],[1,1,1,0,0,0,0,0,0,0,0,0,0],[1,1,1,0,0,0,0,0,0,0,0,0,0],[1,1,1,0,0,0,0,0,0,0,0,0,0],[480,650,580,390,0,0,0,0,0,0,0,0,0],[480,650,580,390,0,0,0,0,0,0,0,0,0],[480,650,580,390,0,0,0,0,0,0,0,0,0]])
c=np.array([18,15,23,12,6800,8700,5300])
d=np.array([[1,1,1,1,0,0,0,0,0,0,0,0,0],[1,1,1,1,0,0,0,0,0,0,0,0,0],[1,1,1,1,0,0,0,0,0,0,0,0,0]])
e=np.array([5,8,4])
x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13=(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None)

res=linprog(a,b,c,d,e,bounds=(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13)) 
print(res)





     con: array([nan, nan, nan])
     fun: -inf
 message: 'If feasible, the problem is (trivially) unbounded due  to a zero column in the constraint matrices. If you wish to check whether the problem is infeasible, turn presolve off.'
     nit: 0
   slack: array([nan, nan, nan, nan, nan, nan, nan])
  status: 3
 success: False
       x: array([ 0.,  0.,  0.,  0., inf, inf, inf, inf, inf, inf, inf, inf,  0.])


In [4]:
import cvxpy as cp

x=cp.Variable((4,4),pos=True) #生成一个变量
obj=cp.Minimize(2800*sum(x[:0])+4500*sum(x[:3,1])+6000*sum(x[:2,2])+7300*x[0,3])
cons=[sum(x[0,:])>=15,
        sum(x[0,1:])+sum(x[2,:3])>=10,
        sum(x[0,2:])+sum(x[1,1:3])+sum(x[2,:2])>=20,
        x[0,3]+x[1,2]+x[2,1]+[3,0]>=12]
prob=cp.Problem(obj,cons)
prob.solve(solver='GLPK_MI')
print("最优解为： ",prob.value)
print("最优解为： \n",x.value)


最优解为：  54000.0
最优解为： 
 [[15. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [ 8. 12. -0. -0.]
 [-0. -0. -0. -0.]]


In [1]:
import  cvxopt
import cvxpy 
print(cvxpy.installed_solvers())

['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCIPY', 'SCS']


In [19]:
import cvxpy as cp
from numpy import array

print(cp.installed_solvers())

['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCIPY', 'SCS']
