In [1]:
import numpy as np 
from scipy.optimize import linprog

a=np.array([-3100,-3100,-3100,-3800,-3800,-3800,-3500,-3500,-3500,-2850,-2850,-2850,0])
b=np.array([[1,1,1,0,0,0,0,0,0,0,0,0,0],[1,1,1,0,0,0,0,0,0,0,0,0,0],[1,1,1,0,0,0,0,0,0,0,0,0,0],[1,1,1,0,0,0,0,0,0,0,0,0,0],[480,650,580,390,0,0,0,0,0,0,0,0,0],[480,650,580,390,0,0,0,0,0,0,0,0,0],[480,650,580,390,0,0,0,0,0,0,0,0,0]])
c=np.array([18,15,23,12,6800,8700,5300])
d=np.array([[1,1,1,1,0,0,0,0,0,0,0,0,0],[1,1,1,1,0,0,0,0,0,0,0,0,0],[1,1,1,1,0,0,0,0,0,0,0,0,0]])
e=np.array([5,8,4])
x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13=(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None)

res=linprog(a,b,c,d,e,bounds=(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13)) 
print(res)





     con: array([nan, nan, nan])
     fun: -inf
 message: 'If feasible, the problem is (trivially) unbounded due  to a zero column in the constraint matrices. If you wish to check whether the problem is infeasible, turn presolve off.'
     nit: 0
   slack: array([nan, nan, nan, nan, nan, nan, nan])
  status: 3
 success: False
       x: array([ 0.,  0.,  0.,  0., inf, inf, inf, inf, inf, inf, inf, inf,  0.])


In [4]:
import cvxpy as cp

x=cp.Variable((4,4),pos=True) #生成一个变量
obj=cp.Minimize(2800*sum(x[:0])+4500*sum(x[:3,1])+6000*sum(x[:2,2])+7300*x[0,3])
cons=[sum(x[0,:])>=15,
        sum(x[0,1:])+sum(x[2,:3])>=10,
        sum(x[0,2:])+sum(x[1,1:3])+sum(x[2,:2])>=20,
        x[0,3]+x[1,2]+x[2,1]+[3,0]>=12]
prob=cp.Problem(obj,cons)
prob.solve(solver='GLPK_MI')
print("最优解为： ",prob.value)
print("最优解为： \n",x.value)


最优解为：  54000.0
最优解为： 
 [[15. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [ 8. 12. -0. -0.]
 [-0. -0. -0. -0.]]


In [1]:
import  cvxopt
import cvxpy 
print(cvxpy.installed_solvers())

['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCIPY', 'SCS']


In [19]:
import cvxpy as cp
from numpy import array

print(cp.installed_solvers())

['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCIPY', 'SCS']


In [6]:
zp=2336812163.78220 
yl=1129474835.240500 
lis=[1129474835.240500,
354275058.750300 ,
1170905938.461000 ,
1402134501.734400 ,
1035986294.190000 ,
304188130.303200 ,
902462083.338600 ,
744407246.643200 ,
329390656.815000 ,
25945870.284800 
]
for yl in lis:
    if yl>=zp:
        print("true"+yl-zp)
    else:
        print("false",zp-yl)

1207337328.5417
1982537105.0319
1165906225.3212
934677662.0477998
1300825869.5921998
2032624033.4789999
1434350080.4435997
1592404917.139
2007421506.9671998
2310866293.4974


In [8]:
lis=[1207337328.5417,
1982537105.0319,
1165906225.3212,
934677662.0477998,
1300825869.5921998,
2032624033.4789999,
1434350080.4435997,
1592404917.139,
2007421506.9671998,
2310866293.4974]
min=lis[0]
for i in range(10):
    if min>lis[i]:
        min=lis[i]
    else: continue
print(min)

934677662.0477998


In [17]:
from itertools import combinations,permutations
lis=[1129474835.240500 ,
329390656.815000 ,
744407246.643200 ,
25945870.284800 ,
354275058.750300 ,
1170905938.461000 ,
1402134501.734400 ,
902462083.338600 ,
304188130.303200 ,
1035986294.190000 
]

zp=2336812163.78220 
result=list(combinations(lis,3))
for i in range(len(result)):
    lis1=list(result[i])
    lis2=lis1[0]+lis1[1]+lis1[2]
    if lis2>=zp:
        print(lis2)
        print(lis1[0],lis1[1])

2629771430.5165
1129474835.2405 329390656.815
2860999993.7899
1129474835.2405 329390656.815
2361327575.3941
1129474835.2405 329390656.815
2494851786.2455
1129474835.2405 329390656.815
3044788020.3447
1129474835.2405 744407246.6432
3276016583.6181
1129474835.2405 744407246.6432
2776344165.2223
1129474835.2405 744407246.6432
2909868376.0737
1129474835.2405 744407246.6432
2557555207.2597
1129474835.2405 25945870.2848
2654655832.4518
1129474835.2405 354275058.7503
2885884395.7251997
1129474835.2405 354275058.7503
2386211977.3294
1129474835.2405 354275058.7503
2519736188.1808
1129474835.2405 354275058.7503
3702515275.4358997
1129474835.2405 1170905938.461
3202842857.0401
1129474835.2405 1170905938.461
2604568904.0046997
1129474835.2405 1170905938.461
3336367067.8915
1129474835.2405 1170905938.461
3434071420.3135004
1129474835.2405 1402134501.7344
2835797467.2781
1129474835.2405 1402134501.7344
3567595631.1649003
1129474835.2405 1402134501.7344
3067923212.7691
1129474835.2405 902462083.3386


In [16]:
lis=[5,
10,
8,
2,
3,
10,
12,
9,
3,
10
]
zp=17
result=list(combinations(lis,3))
for i in range(len(result)):
    lis1=list(result[i])
    lis2=lis1[0]+lis1[1]+lis1[2]
    if lis2<=zp:
        print(lis2)


17
15
16
16
10
17
16
10
17
17
11
17
15
15
16
13
13
14
15
17
14
8
15
15
17
14
15
16
15
16


In [21]:
from itertools import combinations,permutations
lis=[[1129474835.240500,5] ,
[329390656.815000,10] ,
[744407246.643200,8] ,
[25945870.284800,2],
[354275058.750300,3],
[1170905938.461000,10] ,
[1402134501.734400,12] ,
[902462083.338600,9] ,
[304188130.303200,3] ,
[1035986294.190000,10] 
]
lis2={}
zp=2336812163.78220 
j=0
result=list(combinations(lis,3))
for i in range(len(result)):
    lis1=list(result[i])
    mj=lis1[0][0]+lis1[1][0]+lis1[2][0]
    if mj>=zp:
        lis2[j]=result[i]
        j=j+1
    else:
        continue
for i in range(len(lis2)):
    lis3=list(lis2[i])
    zs=lis3[0][1]+lis3[1][1]+lis3[2][1]
    if zs<=17:
        print(lis2[i])

([1129474835.2405, 5], [354275058.7503, 3], [902462083.3386, 9])


In [ ]:
2386211977.329400 
