<img src="./picture/1.png" height="330" width="1000">

<img src="./picture/2.png" height="330" width="1000">

<img src="./picture/3.png" >

In [31]:
import cvxpy as cp 
import numpy as np

x=cp.Variable((6,4),integer=True)

c=np.array([[4,2,3,4],[6,4,5,5],[7,6,7,6],[7,8,8,6],[7,9,8,6],[7,10,8,6]])
#c=np.array([[4,6,7,7,7,7],[2,4,6,8,9,10],[3,5,7,8,8,8],[4,5,6,6,6,6]])
print(cp.multiply(c, x))
obj = cp.Maximize(cp.sum(cp.multiply(c, x)))#如果需要变标量，用这个
#obj=cp.Maximize(sum(c@x))
con=[
    sum(x)>=1,#行求和
    cp.sum(x,axis=1)==1,#列求和
    x>=0,
    x<=1
]
prob=cp.Problem(obj,con)
prob.solve(solver="GLPK_MI")
print("最优解： ",x.value)
print("最优值： ",prob.value)

[[ 4.  2.  3.  4.]
 [ 6.  4.  5.  5.]
 [ 7.  6.  7.  6.]
 [ 7.  8.  8.  6.]
 [ 7.  9.  8.  6.]
 [ 7. 10.  8.  6.]] @ var803
最优解：  [[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]
最优值：  44.0
