# 练习
<img src="./pictures/1.jpg">

In [4]:

import cvxpy as cp

x=cp.Variable((4,4),pos=True) #生成一个变量4*4,pos表示正数
obj=cp.Minimize(2800*sum(x[:0])+4500*sum(x[:3,1])+6000*sum(x[:2,2])+7300*x[0,3])#求最小值所以用Minimize
cons=[sum(x[0,:])>=15,
        sum(x[0,1:])+sum(x[2,:3])>=10,
        sum(x[0,2:])+sum(x[1,1:3])+sum(x[2,:2])>=20,
        x[0,3]+x[1,2]+x[2,1]+[3,0]>=12]
prob=cp.Problem(obj,cons)
prob.solve(solver='GLPK_MI')
print("最优解为： ",prob.value)#结果
print("最优解为： \n",x.value)

最优解为：  54000.0
最优解为： 
 [[15. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [ 8. 12. -0. -0.]
 [-0. -0. -0. -0.]]


In [ ]:
import cvxpy as cp

x=cp.Variable((4,4),pos=True) #生成一个变量
obj=cp.Minimize(2800*sum(x[:0])+4500*sum(x[:3,1])+6000*sum(x[:2,2])+7300*x[0,3])
cons=[sum(x[0,:])>=15,
        sum(x[0,1:])+sum(x[2,:3])>=10,
        sum(x[0,2:])+sum(x[1,1:3])+sum(x[2,:2])>=20,
        x[0,3]+x[1,2]+x[2,1]+[3,0]>=12]
prob=cp.Problem(obj,cons)
prob.solve(solver='GLPK_MI')
print("最优解为： ",prob.value)
print("最优解为： \n",x.value)


# 练习
<img src="./pictures/3.jpg" height="400" width="700">
<img src="./pictures/4.jpg" height="400" width="1000">

In [25]:
import numpy as np
import cvxpy as cp

c1=np.array([-2,-3])
c2=np.array([1,2])
a=np.array([[0.5,0.25],[0.2,0.2],[1,5],[-1,-1]])
b=np.array([8,4,72,-10])
x=cp.Variable(2,pos=True)
obj=cp.Minimize(0.5*(c1+c2)@x)
con=[a@x<=b] #@应该表示分别乘x1，x2
prob=cp.Problem(obj,con)
prob.solve(solver="GLPK_MI")
print("最优解： ",x.value)
print("最优值： ",prob.value)

最优解：  [12.  8.]
最优值：  -10.0


In [34]:
import numpy as np
import cvxpy as cp

c1=np.array([-2,-3])
c2=np.array([1,2])
a=np.array([[0.5,0.25],[0.2,0.2],[1,5],[-1,-1]])
b=np.array([8,4,72,-10])
x=cp.Variable(2,pos=True)
obj1=cp.Minimize(c1@x)
con=[a@x<=b] #@应该表示分别乘x1，x2
prob1=cp.Problem(obj1,con)
prob1.solve(solver="GLPK_MI")
v1=prob1.value
obj2=cp.Minimize(c2@x)
prob2=cp.Problem(obj2,con)
prob2.solve(solver="GLPK_MI")
v2=prob2.value
print("两个目标函数最优解：",v1,v2)
obj3=cp.Minimize((c1@x-v1)**2+(c2@x-v2)**2)
prob3=cp.Problem(obj3,con)
prob1.solve(solver="CVXOPT")
print("解法二最优",x.value)


两个目标函数最优解： -53.0 10.0
解法二最优 [ 7.00000021 12.9999996 ]


In [37]:
import numpy as np
import cvxpy as cp

c1=np.array([-2,-3])
c2=np.array([1,2])
a=np.array([[0.5,0.25],[0.2,0.2],[1,5],[-1,-1]])
b=np.array([8,4,72,-10])
x=cp.Variable(2,pos=True)
obj1=cp.Minimize(c1@x)
con=[a@x<=b] #@应该表示分别乘x1，x2
prob1=cp.Problem(obj1,con)
prob1.solve(solver="GLPK_MI")
v1=prob1.value
obj2=cp.Minimize(c2@x)
print("两个目标函数最优解：",v1)
con.append(c1@x==v1)
prob4=cp.Problem(obj2,con)
prob4.solve(solver="GLPK_MI")
x3=x.value
print(x3)



两个目标函数最优解： -53.0
[ 7. 13.]


# 任务
<img src="./pictures/2.png" height="330" width="1000">

In [10]:
import numpy as np
from scipy.optimize import linprog
c=np.array([-2,-2.5])
aeq=np.array([[1,1]])
beq=np.array([[7]])
x1=(0,5)
x2=(0,5)
res=linprog(c,aeq,beq,bounds=(x1,x2))
print(res)


     con: array([], dtype=float64)
     fun: -16.49999999997455
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([1.13056231e-11])
  status: 0
 success: True
       x: array([2., 5.])


In [27]:
import numpy as np
import cvxpy as cp
x=cp.Variable(2,pos=True)
c1=np.array([-3,-1])
c2=np.array([-1,-2])
obj=cp.Minimize(0.5*(c1+c2)@x)
a=np.array([[1,1],[1,0],[0,1]])
b=np.array([7,5,5])
con=[a@x<=b]
prob=cp.Problem(obj,con)
prob.solve(solver="GLPK_MI")
print('\n======1.线性加权法======\n')
print("最优解： ",x.value)
print("最优值： ",prob.value)



======1.线性加权法======

最优解：  [5. 2.]
最优值：  -13.0



======1.线性加权法======

解法一理想解： [12.  8.]
利润： 44.0
污染排放： -27.999999999999993
