<img src="./线性规划练习3（2）.png">

<img src="./线性规划练习3（3）.png">

<img src="./线性规划练习3.png" >

 c=c(:)是将矩阵变为列向量
> 
>  c=[1 2;3 4];
> 
>  c=c(:);
> 
>  c=1
> 
>  3
> 
>  2
> 
>  4
> 


In [1]:
import numpy as np
from scipy.optimize import linprog
c=np.array([[3100],[3800],[3500],[2850]])                          #列向量可以有 第一步，c为列向量，c为利润
# a=np.ones([1,3])
# print(np.matmul(c,a))
c=c*np.ones([1,3])                                                 #第二步，将c拓展到12个，行表示同一个c，列表示不同c
#print(c)
c= c.flatten('F') #按列降维                                        #带入linprog需要降维，按列降维，因为x是按照行写的[x1j,x2j,x3j,x4j]，按照列展开
#print(c)                                                          #需要按列降维才可以将每一个x系数对应上因为，x降维是一层一层降的，所以对应不同的系数才行
a1=np.zeros([4,12])                                                #在linprog中每一列对应一个未知数例如：[1,2,3,4]对应四个系数，每一行对应一个公式
# print(a1)
for i in range(0,4):
    a1[i,i:13:4]=1                                                # 系数为1，这里行表示设置的i，列表示设置的j对应的公式，因为几个系数必须有几列
#print(a1)                                                        
b1=np.array([[18],[15],[23],[12]])                                #货物重量
a2=np.zeros([3,12])
for i in range(0,3):
    a2[i,4*i:4*i+4]=1
#print(a2)
b2=np.array([[10,16,8]]).T
# print(b2)
bb=np.array([[480,650,580,390]])
a3=np.zeros([3,12])
for j in range(0,3):
    a3[j,4*j:4*j+4]=bb#不确定
bb=bb.T
# print(bb)
b3=np.array([[6800,8700,5300]]).T
a=np.vstack((a1,a2,a3))
#print(a)
b=np.vstack((b1,b2,b3))
# print(b)
aeq=np.zeros([2,12])
aeq[0,0:4]=1/10
aeq[0,4:8]=-1/16
aeq[1,4:8]=1/16
aeq[1,8:12]=-1/8
beq=np.zeros([2,1])
x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12=(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None)

c=linprog(-c,a,b,aeq,beq,bounds=(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12))#不确定
print(c.x.reshape([4,3]))
print(-c.fun)




[[2.97898412e-10 8.57224165e+00 1.42775835e+00]
 [1.11247486e-10 4.78882950e-09 1.35845194e-10]
 [1.29473684e+01 3.05263158e+00 5.24722678e-10]
 [6.42775835e+00 1.57224165e+00 1.88099307e-10]]
121515.78945368329


a1：
[[1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]]
a2:
[[1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]]
a：
[[  1.   0.   0.   0.   1.   0.   0.   0.   1.   0.   0.   0.]
 [  0.   1.   0.   0.   0.   1.   0.   0.   0.   1.   0.   0.]
 [  0.   0.   1.   0.   0.   0.   1.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   1.   0.   0.   0.   1.   0.   0.   0.   1.]
 [  1.   1.   1.   1.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   1.   1.   1.   1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   1.   1.   1.   1.]
 [480. 650. 580. 390.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 480. 650. 580. 390.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 480. 650. 580. 390.]]

In [27]:
import numpy as np
from scipy.optimize import linprog
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("创建a矩阵:\n",a)

print(a[1,[0,2]])

创建a矩阵:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 6]
